eureka:  
  client: 
    serviceUrl: 
    #eureka注册中心地址      
      defaultZone: http://localhost:8888/eureka/
server: 
 #项目端口号 
  port: 8001 
spring:  
  application:  
  #服务名称,随便写   
    name: service-consumer