eureka:  
  client: 
    serviceUrl: 
    #eureka注册中心地址      
      defaultZone: http://localhost:8888/eureka/
server: 
 #项目端口号 
  port: 8001
tomcat:
  max-threads: 30
spring:  
  application:  
  #服务名称,随便写   
    name: service-consumer
    
#启用feign中的hystrix
feign:
  hystrix:
    enable:true
#断路器的超时时间,下级服务返回超出时间则熔断并执行回退机制
##默认=1000,太小,修改为50秒
hystrix:
   command:
     default:
      execution:
       timeout:
        enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 50000
    